# Sadly there is no nice way to have friendly names. As such,
#  the material values are used. For instance, the default tool
#  bindings are scroll tool to bone, which is 352, and the
#  duplicator tool is the stone axe, or 275. test
# 
# Individual tool configuration option descriptions are found
#  in the help/<tool>.txt files. Those files will always have
#  the most up-to-date default settings for each tool.
# 
# debug: <true|false>
#    Don't enable this unless you want a bunch of data dumped
#    to the console logs. Can be useful for validating your
#    config.yml file, as it dumps what it reads.
# 
# permissions: <true|false>
#    While permissions are very handy and often the best way
#    to control the use of tools, some people do not like them.
#    If that is the case, set this to false to disable
#    permission checking.
# 
# tools: bind: <tool>: <id>
#    This gives a mapping of what item to use for what tool.
#    If a tool is not wanted, you can disable it by removing
#    the permission from the (or all) user(s). If you want to
#    run the server without permissions, it is suggested to
#    remove it by adding a '#' to the beginning of the line.
#    However, setting it's value to zero will also disable
#    the tool, it but with a warning to the console.


debug: false
permissions: true
tools:
  bind:
    dupe: 275   # STONE_AXE
    scroll: 352 # BONE
    paint: 341  # SLIME_BALL
    leap: 288   # FEATHER
  dupe:
    replace:
      7: 260    # BEDROCK to APPLE
      8: 326    # WATER to WATER_BUCKET
      9: 326    # STATIONARY_WATER to WATER_BUCKET
      10: 327   # LAVA to LAVA_BUCKET
      11: 327   # STATIONARY_LAVA to LAVA_BUCKET
      78: 332   # SNOW to SNOW_BALL
      104: 361  # PUMPKIN_STEM to PUMPKIN_SEEDS
      105: 362  # MELON_STEM to MELON_SEEDS
    keepData: [6, 17, 18, 31, 35, 43, 44, 98, 263, 351, 373, 374]
  scroll:
    override: false
    allow: [35, 43, 44, 98]
  paint:
    range: false
    distance: 25
    onlyAllow: []
    blockLoad: [7, 8, 9, 10, 11, 46, 75, 90, 92, 93, 94, 95, 119]
    blockOverwrite: [7, 8, 9, 10, 11, 90, 119]
  leap:
    thrust: 8
    cruise: 110
    teleport: false

